#####################################################
# Create an apis_ontology Organisation object from an RDF endpoint.
# Source: DNB, https://d-nb.info
#####################################################
superclass = "apis_ontology.models.Organisation"
regex = "https://d-nb.info.*"
[[attributes]]
# name
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?name
WHERE {
  ?subject gndo:preferredNameForTheCorporateBody ?name
}
"""
[[attributes]]
# start_date_written
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?start_date_written
WHERE {
  ?subject gndo:dateOfEstablishment ?start_date_written
}
"""
[[attributes]]
# end_date_written
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?end_date_written
WHERE {
  ?subject gndo:dateOfTermination ?end_date_written
}
"""
