######################################################
# Create an apis_ontology Person object from an RDF endpoint.
# Source: DNB, https://d-nb.info
######################################################
superclass = "apis_ontology.models.Person"
regex = "https://d-nb.info.*"
[[attributes]]
# name
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?surname
WHERE {
  ?subject gndo:preferredNameEntityForThePerson/gndo:surname ?name .
  BIND(?name AS ?surname)
}
"""
[[attributes]]
# first_name
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?forename
WHERE {
  ?subject gndo:preferredNameEntityForThePerson/gndo:forename ?first_name .
  BIND(?first_name as ?forename)
}
"""
[[attributes]]
# first_name
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?fallback_name
WHERE {
  OPTIONAL{?subject gndo:preferredNameForThePerson ?fallback_name1} .
  OPTIONAL{?subject gndo:preferredNameForTheSubjectHeading ?fallback_name2} .
  OPTIONAL{?subject gndo:preferredNameForTheCorporateBody ?fallback_name3} .
  BIND(COALESCE(?fallback_name1, ?fallback_name2, ?fallback_name3) as ?fallback_name)
}
"""
