####################################################
# Create an apis_ontology Place object from an RDF endpoint.
# Source: Geonames, https://sws.geonames.org
####################################################
superclass = "apis_ontology.models.Place"
regex = "https://sws.geonames.org.*"
[[attributes]]
# name
#FILTER (LANGMATCHES(LANG(?prefName), "de") || LANGMATCHES(LANG(?prefName), "en") || LANG(?prefName) = "")
sparql = """
PREFIX gn: <http://www.geonames.org/ontology#>
SELECT ?name
WHERE {
  OPTIONAL {
    ?subject gn:name ?gnname_de .
    FILTER(LANGMATCHES(LANG(?gnname_de), "de"))
  }
  OPTIONAL {
   ?subject gn:officialName ?officialName_de
    FILTER(LANGMATCHES(LANG(?officialName_de), "de"))
  }
  OPTIONAL {
    ?subject gn:alternateName ?alternateName_de
    FILTER(LANGMATCHES(LANG(?alternateName_de), "de"))
  }
  OPTIONAL {
    ?subject gn:name ?gnname .
  }
  OPTIONAL {
   ?subject gn:officialName ?officialName
  }
  OPTIONAL {
    ?subject gn:alternateName ?alternateName
  }
  BIND(COALESCE(?gnname_de, ?officialName_de, ?alternateName_de, ?gnname, ?officialName, ?alternateName) AS ?name)
}
"""
[[attributes]]
# lat
sparql = """
PREFIX wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
SELECT ?latitude
WHERE {
  ?subject wgs84_pos:lat ?latitude.
  ?subject wgs84_pos:long ?longitude
}
"""
[[attributes]]
# long
sparql = """
PREFIX wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
SELECT ?longitude
WHERE {
  ?subject wgs84_pos:lat ?latitude.
  ?subject wgs84_pos:long ?longitude
}
"""
