# SPDX-FileCopyrightText: 2024 K Kollmann
# SPDX-License-Identifier: MIT

version: 2
updates:
    # dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # workflows/actions are assumed to be in (have as root) .github/workflows
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Frischmuth project dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
      include: "scope"
    allow:
      # limit updates to direct dependencies, so dependencies of direct
      # dependencies (like APIS Core) aren't included
      - dependency-type: "direct"
# TODO re-enable groups once Dependabot learns to not create overly long lines
# see https://github.com/dependabot/dependabot-core/issues/2445
#    groups:
#      apis-dependencies:
#        patterns:
#          - "apis-*"
#      project-dev-dependencies:
#        # includes all [tool.poetry.group.*.dependencies]
#        dependency-type: development
#      project-dependencies:
#        dependency-type: production
#      vulnerabilities:
#        applies-to: security-updates
#        patterns:
#          - "*"
