# Generated by Django 4.2.7 on 2023-12-11 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0003_alter_work_data_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="work",
            options={
                "ordering": ["-siglum"],
                "verbose_name": "werk",
                "verbose_name_plural": "werke",
            },
        ),
        migrations.RemoveField(
            model_name="work",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="work",
            name="title",
        ),
    ]
