# Generated by Django 4.2.7 on 2023-12-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0004_alter_work_options_remove_work_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Untertitel"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titel"
            ),
        ),
    ]
