# Generated by Django 4.2.7 on 2023-12-11 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0005_work_subtitle_work_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="work",
            options={
                "ordering": ["title", "subtitle", "-siglum"],
                "verbose_name": "werk",
                "verbose_name_plural": "werke",
            },
        ),
    ]
