# Generated by Django 4.2.7 on 2023-12-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apis_metainfo", "0008_alter_rootobject_self_contenttype"),
        ("apis_ontology", "0006_alter_work_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expression",
            fields=[
                (
                    "rootobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.rootobject",
                    ),
                ),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("created", "neu angelegt"),
                            ("edited", "reine Datenänderung"),
                            ("worked_on", "in Bearbeitung"),
                            ("awaiting_review", "Review erbeten"),
                            ("reviewed", "Review abgeschlossen"),
                            ("approved", "für VÖ freigegeben"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Bearbeitungsstatus",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Titel"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Untertitel"
                    ),
                ),
                (
                    "year_of_publication",
                    models.DateField(
                        blank=True,
                        help_text="Eingabe muss im Format YYYY-MM-DD erfolgen",
                        null=True,
                        verbose_name="Erscheinungsjahr",
                    ),
                ),
                (
                    "page_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Seitenanzahl einer relevanten Manifestation",
                        null=True,
                        verbose_name="Seitenanzahl",
                    ),
                ),
                (
                    "relevant_pages",
                    models.CharField(
                        blank=True, null=True, verbose_name="Forschungsrelevante Seiten"
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expressions",
                        to="apis_ontology.datasource",
                        verbose_name="Datenquelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "werksexpression",
                "verbose_name_plural": "werksexpressionen",
                "ordering": ["title", "subtitle"],
            },
            bases=("apis_metainfo.rootobject", models.Model),
        ),
    ]
