# Generated by Django 4.2.7 on 2023-12-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apis_metainfo", "0008_alter_rootobject_self_contenttype"),
        ("apis_ontology", "0007_expression"),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "rootobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.rootobject",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Anschrift"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Webseite"
                    ),
                ),
            ],
            options={
                "verbose_name": "archiv",
                "verbose_name_plural": "archive",
            },
            bases=("apis_metainfo.rootobject", models.Model),
        ),
        migrations.CreateModel(
            name="PhysicalObject",
            fields=[
                (
                    "rootobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.rootobject",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
            ],
            options={
                "verbose_name": "vorlassobjekt",
                "verbose_name_plural": "vorlassobjekte",
            },
            bases=("apis_metainfo.rootobject", models.Model),
        ),
    ]
