# Generated by Django 4.2.7 on 2023-12-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0008_archive_physicalobject"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archives",
                to="apis_ontology.datasource",
                verbose_name="Datenquelle",
            ),
        ),
        migrations.AddField(
            model_name="physicalobject",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="physicalobjects",
                to="apis_ontology.datasource",
                verbose_name="Datenquelle",
            ),
        ),
    ]
