# Generated by Django 4.2.7 on 2023-12-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apis_metainfo", "0008_alter_rootobject_self_contenttype"),
        ("apis_ontology", "0012_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "rootobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.rootobject",
                    ),
                ),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("created", "neu angelegt"),
                            ("edited", "reine Datenänderung"),
                            ("worked_on", "in Bearbeitung"),
                            ("awaiting_review", "Review erbeten"),
                            ("reviewed", "Review abgeschlossen"),
                            ("approved", "für VÖ freigegeben"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Bearbeitungsstatus",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topics",
                        to="apis_ontology.datasource",
                        verbose_name="Datenquelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "thema",
                "verbose_name_plural": "themen",
                "ordering": ["name"],
            },
            bases=("apis_metainfo.rootobject", models.Model),
        ),
        migrations.CreateModel(
            name="ResearchPerspective",
            fields=[
                (
                    "rootobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.rootobject",
                    ),
                ),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("created", "neu angelegt"),
                            ("edited", "reine Datenänderung"),
                            ("worked_on", "in Bearbeitung"),
                            ("awaiting_review", "Review erbeten"),
                            ("reviewed", "Review abgeschlossen"),
                            ("approved", "für VÖ freigegeben"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Bearbeitungsstatus",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="researchperspectives",
                        to="apis_ontology.datasource",
                        verbose_name="Datenquelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "forschungshinsicht",
                "verbose_name_plural": "forschungshinsichten",
                "ordering": ["name"],
            },
            bases=("apis_metainfo.rootobject", models.Model),
        ),
        migrations.CreateModel(
            name="Interpretatem",
            fields=[
                (
                    "rootobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.rootobject",
                    ),
                ),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("created", "neu angelegt"),
                            ("edited", "reine Datenänderung"),
                            ("worked_on", "in Bearbeitung"),
                            ("awaiting_review", "Review erbeten"),
                            ("reviewed", "Review abgeschlossen"),
                            ("approved", "für VÖ freigegeben"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Bearbeitungsstatus",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interpretatems",
                        to="apis_ontology.datasource",
                        verbose_name="Datenquelle",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "interpretateme",
                "ordering": ["name"],
            },
            bases=("apis_metainfo.rootobject", models.Model),
        ),
    ]
