# Generated by Django 4.2.7 on 2023-12-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0013_topic_researchperspective_interpretatem"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Beschreibung"),
        ),
    ]
