# Generated by Django 4.2.7 on 2023-12-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0015_topic_alternative_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchperspective",
            name="alternative_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Alternativer Name"
            ),
        ),
    ]
