# Generated by Django 4.2.7 on 2023-12-11 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0017_worktype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worktype",
            options={
                "ordering": ["name", "name_plural", "alternative_name"],
                "verbose_name": "werktyp",
                "verbose_name_plural": "werktypen",
            },
        ),
    ]
