# Generated by Django 4.2.8 on 2023-12-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0018_alter_worktype_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archives",
                to="apis_ontology.datasource",
                verbose_name="Datenquelle",
            ),
        ),
        migrations.AlterField(
            model_name="physicalobject",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="physicalobjects",
                to="apis_ontology.datasource",
                verbose_name="Datenquelle",
            ),
        ),
    ]
