# Generated by Django 4.2.8 on 2023-12-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0019_alter_archive_data_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="progress_status",
            field=models.CharField(
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                max_length=255,
                null=True,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="progress_status",
            field=models.CharField(
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                max_length=255,
                null=True,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="interpretatem",
            name="progress_status",
            field=models.CharField(
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                max_length=255,
                null=True,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="metacharacter",
            name="progress_status",
            field=models.CharField(
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                max_length=255,
                null=True,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="progress_status",
            field=models.CharField(
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                max_length=255,
                null=True,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="progress_status",
            field=models.CharField(
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                max_length=255,
                null=True,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="progress_status",
            field=models.CharField(
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                max_length=255,
                null=True,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="researchperspective",
            name="progress_status",
            field=models.CharField(
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                max_length=255,
                null=True,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="progress_status",
            field=models.CharField(
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                max_length=255,
                null=True,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="progress_status",
            field=models.CharField(
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                max_length=255,
                null=True,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="progress_status",
            field=models.CharField(
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                max_length=255,
                null=True,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
    ]
