# Generated by Django 4.2.9 on 2024-01-17 08:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0021_alter_character_progress_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="manifestation_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("first_edition", "Erstausgabe"),
                    ("reference_edition", "Referenzausgabe"),
                ],
                help_text="Zur Markierung speziell relevanter Manifestationen",
                max_length=255,
                null=True,
                verbose_name="Ausgabetyp",
            ),
        ),
    ]
