# Generated by Django 4.2.9 on 2024-01-17 08:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0022_expression_manifestation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="fictionality",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("fictional_character", "fiktive Figur"),
                    ("historical_character", "historische Figur"),
                    ("mythical_character", "mythologische Figur"),
                ],
                help_text="Faktizität vs. Fiktionalität",
                max_length=255,
                null=True,
                verbose_name="Erfindungsgrad",
            ),
        ),
    ]
