# Generated by Django 4.2.9 on 2024-01-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0024_rename_year_of_publication_expression_publication_date",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="publication_date",
            field=models.DateField(
                blank=True,
                help_text="Eingabe muss im Format YYYY-MM-DD erfolgen",
                null=True,
                verbose_name="Erscheinungsdatum",
            ),
        ),
    ]
