# Generated by Django 4.2.9 on 2024-01-22 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0025_alter_expression_publication_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expression",
            old_name="manifestation_type",
            new_name="edition_type",
        ),
    ]
