# Generated by Django 4.2.9 on 2024-01-22 09:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0026_rename_manifestation_type_expression_edition_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="edition_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("first_edition", "Erstausgabe"),
                    ("reference_edition", "Referenzausgabe"),
                ],
                help_text="Zur Markierung speziell relevanter Ausgaben",
                max_length=255,
                null=True,
                verbose_name="Ausgabetyp",
            ),
        ),
    ]
