# Generated by Django 4.2.9 on 2024-01-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0027_alter_expression_edition_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalobject",
            name="vorlass_doc_reference",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                null=True,
                verbose_name="Vorlassdokument-Referenz",
            ),
        ),
    ]
