# Generated by Django 4.2.10 on 2024-02-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0028_physicalobject_vorlass_doc_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="siglum",
            field=models.CharField(
                blank=True, max_length=6, null=True, unique=True, verbose_name="Sigle"
            ),
        ),
    ]
