# Generated by Django 4.2.10 on 2024-02-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0029_alter_work_siglum"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="issue",
            field=models.CharField(
                blank=True,
                help_text="Nummer/Kennung einer Ausgabe eines periodischen Mediums",
                max_length=30,
                null=True,
                verbose_name="(Zeitungs)Ausgabe",
            ),
        ),
    ]
