# Generated by Django 4.2.10 on 2024-02-07 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0030_expression_issue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expression",
            old_name="publication_date",
            new_name="publication_date_iso",
        ),
    ]
