# Generated by Django 4.2.10 on 2024-02-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0032_alter_expression_publication_date_iso"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="publication_date",
            field=models.CharField(
                blank=True,
                help_text="Eingabe sollte im Format YYYY-MM-DD erfolgen",
                null=True,
                verbose_name="Erscheinungsdatum (freie Eingabe)",
            ),
        ),
    ]
