# Generated by Django 4.2.10 on 2024-02-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0036_alter_expression_publication_date_iso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="publication_date",
            field=models.CharField(
                blank=True,
                help_text="Erlaubte Formatvariationen u.a. 1.1.1920, 12/2010, 1999-12-23,...",
                null=True,
                verbose_name="Erscheinungsdatum",
            ),
        ),
    ]
