# Generated by Django 4.2.10 on 2024-03-04 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0037_alter_expression_publication_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={"verbose_name": "figur", "verbose_name_plural": "figuren"},
        ),
        migrations.AlterModelOptions(
            name="expression",
            options={
                "verbose_name": "werksexpression",
                "verbose_name_plural": "werksexpressionen",
            },
        ),
        migrations.AlterModelOptions(
            name="interpretatem",
            options={"verbose_name_plural": "interpretateme"},
        ),
        migrations.AlterModelOptions(
            name="metacharacter",
            options={"verbose_name": "metafigur", "verbose_name_plural": "metafiguren"},
        ),
        migrations.AlterModelOptions(
            name="organisation",
            options={
                "verbose_name": "körperschaft",
                "verbose_name_plural": "körperschaften",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "personen"},
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "ort", "verbose_name_plural": "orte"},
        ),
        migrations.AlterModelOptions(
            name="researchperspective",
            options={
                "verbose_name": "forschungshinsicht",
                "verbose_name_plural": "forschungshinsichten",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "thema", "verbose_name_plural": "themen"},
        ),
        migrations.AlterModelOptions(
            name="work",
            options={"verbose_name": "werk", "verbose_name_plural": "werke"},
        ),
        migrations.AlterModelOptions(
            name="worktype",
            options={"verbose_name": "werktyp", "verbose_name_plural": "werktypen"},
        ),
    ]
