# Generated by Django 4.2.11 on 2024-03-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0038_alter_character_options_alter_expression_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="character",
            name="alternative_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Alternativer Name"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="character",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Vorname"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nachname"
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="expression",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Untertitel"
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Titel"
            ),
        ),
        migrations.AlterField(
            model_name="interpretatem",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="metacharacter",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="alternative_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Alternativer Name"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="person",
            name="alternative_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Alternativer Name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Vorname"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nachname"
            ),
        ),
        migrations.AlterField(
            model_name="physicalobject",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="place",
            name="alternative_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Alternativer Name"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="researchperspective",
            name="alternative_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Alternativer Name"
            ),
        ),
        migrations.AlterField(
            model_name="researchperspective",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="alternative_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Alternativer Name"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="work",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Untertitel"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Titel"
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="alternative_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Alternativer Name"
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
    ]
