# Generated by Django 4.2.11 on 2024-03-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0040_archive_name_interpretatem_name_metacharacter_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                max_length=255,
                null=True,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
    ]
