# Generated by Django 4.2.11 on 2024-03-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0041_archive_progress_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="fallback_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Namens-Ersatzfeld, falls weder Vor- noch Nachname eindeutig als solche festgelegt bzw. eingegeben werden können",
                max_length=255,
                verbose_name="Uneindeutiger Name",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="fallback_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Namens-Ersatzfeld, falls weder Vor- noch Nachname eindeutig als solche festgelegt bzw. eingegeben werden können",
                max_length=255,
                verbose_name="Uneindeutiger Name",
            ),
        ),
    ]
