# Generated by Django 4.2.11 on 2024-03-12 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0042_character_fallback_name_person_fallback_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="first_name",
            new_name="forename",
        ),
        migrations.RenameField(
            model_name="character",
            old_name="last_name",
            new_name="surname",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="first_name",
            new_name="forename",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="last_name",
            new_name="surname",
        ),
    ]
