# Generated by Django 4.2.11 on 2024-03-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0043_rename_first_name_character_forename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Feld für interne Notizen",
                max_length=1024,
                verbose_name="Notiz",
            ),
        ),
    ]
