# Generated by Django 4.2.11 on 2024-03-27 14:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0044_expression_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Anschrift"
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                default="",
                max_length=255,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="website",
            field=models.URLField(
                blank=True, default="", max_length=255, verbose_name="Webseite"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="fictionality",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("fictional_character", "fiktive Figur"),
                    ("historical_character", "historische Figur"),
                    ("mythical_character", "mythologische Figur"),
                ],
                default="",
                help_text="Faktizität vs. Fiktionalität",
                max_length=255,
                verbose_name="Erfindungsgrad",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                default="",
                max_length=255,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="relevancy",
            field=models.CharField(
                choices=[
                    ("protagonist", "Hauptfigur"),
                    ("supporting_character", "Nebenfigur"),
                    ("referenced_character", "erwähnte Figur"),
                ],
                default="",
                help_text="Bedeutsamkeit für den Text, Erzählfokus",
                max_length=255,
                verbose_name="Relevanz",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="edition_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("first_edition", "Erstausgabe"),
                    ("reference_edition", "Referenzausgabe"),
                ],
                default="",
                help_text="Zur Markierung speziell relevanter Ausgaben",
                max_length=255,
                verbose_name="Ausgabetyp",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="issue",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nummer/Kennung einer Ausgabe eines periodischen Mediums",
                max_length=30,
                verbose_name="(Zeitungs)Ausgabe",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                default="",
                max_length=255,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="publication_date",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Erlaubte Formatvariationen u.a. 1.1.1920, 12/2010, 1999-12-23,...",
                verbose_name="Erscheinungsdatum",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="relevant_pages",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Eingabe muss im Format "X-Y" erfolgen, z.B. 5-12',
                verbose_name="Forschungsrelevante Seiten",
            ),
        ),
        migrations.AlterField(
            model_name="interpretatem",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                default="",
                max_length=255,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="metacharacter",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                default="",
                max_length=255,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                default="",
                max_length=255,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="website",
            field=models.URLField(
                blank=True, default="", max_length=255, verbose_name="Webseite"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                default="",
                max_length=255,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="physicalobject",
            name="vorlass_doc_reference",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=255,
                verbose_name="Vorlassdokument-Referenz",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                default="",
                max_length=255,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="researchperspective",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                default="",
                max_length=255,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                default="",
                max_length=255,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="context",
            field=models.TextField(
                blank=True, default="", verbose_name="Entstehungskontext"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="figure_speech",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direct_quotation", "direkt zitierend"),
                    ("direct_figure_speech", "autonome, direkte Figurenrede"),
                    ("direct_speech", "direkte Rede"),
                    ("indirect_speech", "indirekte Rede"),
                    ("narrated_monologue", "erlebte Rede"),
                ],
                default="",
                max_length=255,
                verbose_name="Figurenrede",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="focalization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zero", "Nullfokalisierung"),
                    ("internal_variable", "interne Fokalisierung – variabel"),
                    ("internal_fixed", "interne Fokalisierung – fixiert"),
                    ("external", "externe Fokalisierung"),
                ],
                default="",
                max_length=255,
                verbose_name="Fokalisierung",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="historical_events",
            field=models.TextField(
                blank=True, default="", verbose_name="Historischer Kontext"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_chronology",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prior", "früheres Erzählen"),
                    ("simultaneous", "gleichzeitiges Erzählen"),
                    ("subsequent", "späteres Erzählen"),
                ],
                default="",
                max_length=255,
                verbose_name="Zeitpunkt des Erzählens",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extra", "extradiegetisch"),
                    ("intra", "intradiegetisch"),
                    ("meta", "metadiegetisch"),
                ],
                default="",
                max_length=255,
                verbose_name="Ort des Erzählens",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_situation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("authorial", "auktorial"),
                    ("neutral", "neutral"),
                    ("figural", "personal"),
                    ("first-person", "Ich-Erzähler*in"),
                ],
                default="",
                max_length=255,
                verbose_name="Erzählperspektive",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_voice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("heterodiegetic", "heterodiegetisches Erzählen"),
                    (
                        "homodiegetic_uninvolved",
                        "homodiegetisches Erzählen – unbeteiligter Beobachter:in",
                    ),
                    (
                        "homodiegetic_participant",
                        "homodiegetisches Erzählen – beteiligter Beobachter:in",
                    ),
                    (
                        "homodiegetic_character",
                        "homodiegetisches Erzählen – Nebenfigur",
                    ),
                    (
                        "homodiegetic_protagonist",
                        "homodiegetisches Erzählen – Hauptfigur",
                    ),
                ],
                default="",
                max_length=255,
                verbose_name="Stellung des:der Erzähler:in zum Geschehen",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                default="",
                max_length=255,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="representation_of_thought",
            field=models.CharField(
                blank=True,
                choices=[
                    ("quoted_monologue", "Zitat"),
                    ("psycho_narration", "erzählter Monolog"),
                    ("autonomous_monologue", "autonomer Monolog"),
                    ("stream_of_consciousness", "Bewusstseinsstrom"),
                ],
                default="",
                max_length=255,
                verbose_name="Darstellung von Gedanken",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Kurzzusammenfassung",
                max_length=1024,
                verbose_name="Teaser",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="temporal_duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scene", "Szene"),
                    ("stretch", "Dehnung"),
                    ("summary", "Raffung"),
                    ("ellipsis", "Ellipse"),
                    ("pause", "Pause"),
                ],
                default="",
                max_length=255,
                verbose_name="Dauer",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="temporal_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("singulative", "singulativ"),
                    ("repetitive", "repetitiv"),
                    ("iterative", "iterativ"),
                ],
                default="",
                max_length=255,
                verbose_name="Frequenz",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="temporal_order",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chronological", "chronologisch"),
                    ("anachronic", "anachronisch"),
                    ("achronic", "achronisch"),
                ],
                default="",
                max_length=255,
                verbose_name="Erzählordnung",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="text_analysis",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Fließtext",
                verbose_name="Textanalyse",
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="name_plural",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Pluralform"
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="progress_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "neu angelegt"),
                    ("edited", "reine Datenänderung"),
                    ("verify_data", "dubios"),
                    ("worked_on", "in Bearbeitung"),
                    ("awaiting_review", "Review erbeten"),
                    ("reviewed", "Review abgeschlossen"),
                    ("approved", "für VÖ freigegeben"),
                ],
                default="",
                max_length=255,
                verbose_name="Bearbeitungsstatus",
            ),
        ),
    ]
