# Generated by Django 4.2.11 on 2024-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0045_alter_archive_location_alter_archive_progress_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="isbn",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="ISBN"
            ),
        ),
    ]
