# Generated by Django 4.2.11 on 2024-03-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0046_expression_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deu", "Deutsch"),
                    ("eng", "Englisch"),
                    ("fra", "Französisch"),
                ],
                default="",
                max_length=3,
                verbose_name="Sprache",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deu", "Deutsch"),
                    ("eng", "Englisch"),
                    ("fra", "Französisch"),
                ],
                default="",
                max_length=3,
                verbose_name="Sprache",
            ),
        ),
    ]
