# Generated by Django 4.2.11 on 2024-03-28 15:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0048_alter_expression_language_alter_work_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="language",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("deu", "Deutsch"),
                    ("eng", "Englisch"),
                    ("fra", "Französisch"),
                ],
                default="",
                max_length=255,
                verbose_name="Sprache",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="language",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("deu", "Deutsch"),
                    ("eng", "Englisch"),
                    ("fra", "Französisch"),
                ],
                default="",
                max_length=255,
                verbose_name="Sprache",
            ),
        ),
    ]
