# Generated by Django 4.2.11 on 2024-03-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0049_alter_expression_language_alter_work_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="edition",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Bsp.: 1. Aufl., deutsche Erstausg.",
                max_length=255,
                verbose_name="Ausgabe (Print-/Druckausgabe)",
            ),
        ),
    ]
