# Generated by Django 4.2.11 on 2024-03-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0050_expression_edition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="issue",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nummer/Kennung einer Ausgabe eines periodischen Mediums",
                max_length=30,
                verbose_name="Zeitungsnummer",
            ),
        ),
    ]
