# Generated by Django 4.2.11 on 2024-04-02 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0052_work_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expression",
            old_name="publication_date",
            new_name="publication_date_manual_input",
        ),
    ]
