# Generated by Django 4.2.11 on 2024-04-02 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0053_rename_publication_date_expression_publication_date_manual_input",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="expression",
            old_name="publication_date_iso",
            new_name="publication_date_iso_formatted",
        ),
    ]
