# Generated by Django 4.2.11 on 2024-04-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0054_rename_publication_date_iso_expression_publication_date_iso_formatted",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="publication_date_iso_formatted",
            field=models.DateField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Erscheinungsdatum (ISO-Format)",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="publication_date_manual_input",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Erlaubte Formatvariationen u.a. 1.1.1920, 12/2010, 1999-12-23,...",
                verbose_name="Erscheinungsdatum (manuelle Eingabe)",
            ),
        ),
    ]
