# Generated by Django 4.2.11 on 2024-04-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0056_researchperspective_notes_topic_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="volume",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Band"
            ),
        ),
    ]
