# Generated by Django 4.2.13 on 2024-06-10 10:27

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0060_versionworktype_string_identifier_and_more"),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
