# Generated by Django 4.2.13 on 2024-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0062_alter_expression_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionwork",
            name="figure_speech",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direct_quotation", "direkt zitierend"),
                    ("direct_figure_speech", "autonome, direkte Figurenrede"),
                    ("direct_speech", "direkte Rede"),
                    ("indirect_speech", "indirekte Rede"),
                    ("narrated_monologue", "erlebte Rede"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Figurenrede (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="focalization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zero", "Nullfokalisierung"),
                    ("internal_variable", "interne Fokalisierung – variabel"),
                    ("internal_fixed", "interne Fokalisierung – fixiert"),
                    ("external", "externe Fokalisierung"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Fokalisierung (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="narrative_chronology",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prior", "früheres Erzählen"),
                    ("simultaneous", "gleichzeitiges Erzählen"),
                    ("subsequent", "späteres Erzählen"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Zeitpunkt des Erzählens (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="narrative_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extra", "extradiegetisch"),
                    ("intra", "intradiegetisch"),
                    ("meta", "metadiegetisch"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Ort des Erzählens (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="narrative_situation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("authorial", "auktorial"),
                    ("neutral", "neutral"),
                    ("figural", "personal"),
                    ("first-person", "Ich-Erzähler*in"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Erzählperspektive (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="narrative_voice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("heterodiegetic", "heterodiegetisches Erzählen"),
                    (
                        "homodiegetic_uninvolved",
                        "homodiegetisches Erzählen – unbeteiligter Beobachter:in",
                    ),
                    (
                        "homodiegetic_participant",
                        "homodiegetisches Erzählen – beteiligter Beobachter:in",
                    ),
                    (
                        "homodiegetic_character",
                        "homodiegetisches Erzählen – Nebenfigur",
                    ),
                    (
                        "homodiegetic_protagonist",
                        "homodiegetisches Erzählen – Hauptfigur",
                    ),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Stellung des:der Erzähler:in zum Geschehen (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="representation_of_thought",
            field=models.CharField(
                blank=True,
                choices=[
                    ("quoted_monologue", "Zitat"),
                    ("psycho_narration", "erzählter Monolog"),
                    ("autonomous_monologue", "autonomer Monolog"),
                    ("stream_of_consciousness", "Bewusstseinsstrom"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Darstellung von Gedanken (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="temporal_duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scene", "Szene"),
                    ("stretch", "Dehnung"),
                    ("summary", "Raffung"),
                    ("ellipsis", "Ellipse"),
                    ("pause", "Pause"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Dauer (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="temporal_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("singulative", "singulativ"),
                    ("repetitive", "repetitiv"),
                    ("iterative", "iterativ"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Frequenz (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="temporal_order",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chronological", "chronologisch"),
                    ("anachronic", "anachronisch"),
                    ("achronic", "achronisch"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Erzählordnung (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="figure_speech",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direct_quotation", "direkt zitierend"),
                    ("direct_figure_speech", "autonome, direkte Figurenrede"),
                    ("direct_speech", "direkte Rede"),
                    ("indirect_speech", "indirekte Rede"),
                    ("narrated_monologue", "erlebte Rede"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Figurenrede (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="focalization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zero", "Nullfokalisierung"),
                    ("internal_variable", "interne Fokalisierung – variabel"),
                    ("internal_fixed", "interne Fokalisierung – fixiert"),
                    ("external", "externe Fokalisierung"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Fokalisierung (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_chronology",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prior", "früheres Erzählen"),
                    ("simultaneous", "gleichzeitiges Erzählen"),
                    ("subsequent", "späteres Erzählen"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Zeitpunkt des Erzählens (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extra", "extradiegetisch"),
                    ("intra", "intradiegetisch"),
                    ("meta", "metadiegetisch"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Ort des Erzählens (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_situation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("authorial", "auktorial"),
                    ("neutral", "neutral"),
                    ("figural", "personal"),
                    ("first-person", "Ich-Erzähler*in"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Erzählperspektive (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_voice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("heterodiegetic", "heterodiegetisches Erzählen"),
                    (
                        "homodiegetic_uninvolved",
                        "homodiegetisches Erzählen – unbeteiligter Beobachter:in",
                    ),
                    (
                        "homodiegetic_participant",
                        "homodiegetisches Erzählen – beteiligter Beobachter:in",
                    ),
                    (
                        "homodiegetic_character",
                        "homodiegetisches Erzählen – Nebenfigur",
                    ),
                    (
                        "homodiegetic_protagonist",
                        "homodiegetisches Erzählen – Hauptfigur",
                    ),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Stellung des:der Erzähler:in zum Geschehen (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="representation_of_thought",
            field=models.CharField(
                blank=True,
                choices=[
                    ("quoted_monologue", "Zitat"),
                    ("psycho_narration", "erzählter Monolog"),
                    ("autonomous_monologue", "autonomer Monolog"),
                    ("stream_of_consciousness", "Bewusstseinsstrom"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Darstellung von Gedanken (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="temporal_duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scene", "Szene"),
                    ("stretch", "Dehnung"),
                    ("summary", "Raffung"),
                    ("ellipsis", "Ellipse"),
                    ("pause", "Pause"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Dauer (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="temporal_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("singulative", "singulativ"),
                    ("repetitive", "repetitiv"),
                    ("iterative", "iterativ"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Frequenz (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="temporal_order",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chronological", "chronologisch"),
                    ("anachronic", "anachronisch"),
                    ("achronic", "achronisch"),
                ],
                default="",
                editable=False,
                max_length=255,
                verbose_name="Erzählordnung (deprecated)",
            ),
        ),
    ]
