# Generated by Django 4.2.13 on 2024-07-17 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0063_alter_versionwork_figure_speech_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="versionwork",
            name="analysis_figure_speech",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("direct_quotation", "direkt zitierend"),
                        ("direct_figure_speech", "autonome, direkte Figurenrede"),
                        ("direct_speech", "direkte Rede"),
                        ("indirect_speech", "indirekte Rede"),
                        ("narrated_monologue", "erlebte Rede"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Figurenrede",
            ),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="analysis_focalization",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("zero", "Nullfokalisierung"),
                        ("internal_variable", "interne Fokalisierung – variabel"),
                        ("internal_fixed", "interne Fokalisierung – fixiert"),
                        ("external", "externe Fokalisierung"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Fokalisierung",
            ),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="analysis_narrative_chronology",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("prior", "früheres Erzählen"),
                        ("simultaneous", "gleichzeitiges Erzählen"),
                        ("subsequent", "späteres Erzählen"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Zeitpunkt des Erzählens",
            ),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="analysis_narrative_level",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("extra", "extradiegetisch"),
                        ("intra", "intradiegetisch"),
                        ("meta", "metadiegetisch"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Ort des Erzählens",
            ),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="analysis_narrative_situation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("authorial", "auktorial"),
                        ("neutral", "neutral"),
                        ("figural", "personal"),
                        ("first-person", "Ich-Erzähler*in"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Erzählperspektive",
            ),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="analysis_narrative_voice",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("heterodiegetic", "heterodiegetisches Erzählen"),
                        (
                            "homodiegetic_uninvolved",
                            "homodiegetisches Erzählen – unbeteiligter Beobachter:in",
                        ),
                        (
                            "homodiegetic_participant",
                            "homodiegetisches Erzählen – beteiligter Beobachter:in",
                        ),
                        (
                            "homodiegetic_character",
                            "homodiegetisches Erzählen – Nebenfigur",
                        ),
                        (
                            "homodiegetic_protagonist",
                            "homodiegetisches Erzählen – Hauptfigur",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Stellung des:der Erzähler:in zum Geschehen",
            ),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="analysis_representation_of_thought",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("quoted_monologue", "Zitat"),
                        ("psycho_narration", "erzählter Monolog"),
                        ("autonomous_monologue", "autonomer Monolog"),
                        ("stream_of_consciousness", "Bewusstseinsstrom"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Darstellung von Gedanken",
            ),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="analysis_temporal_duration",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("scene", "Szene"),
                        ("stretch", "Dehnung"),
                        ("summary", "Raffung"),
                        ("ellipsis", "Ellipse"),
                        ("pause", "Pause"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Dauer",
            ),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="analysis_temporal_frequency",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("singulative", "singulativ"),
                        ("repetitive", "repetitiv"),
                        ("iterative", "iterativ"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Frequenz",
            ),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="analysis_temporal_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("chronological", "chronologisch"),
                        ("anachronic", "anachronisch"),
                        ("achronic", "achronisch"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Erzählordnung",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="analysis_figure_speech",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("direct_quotation", "direkt zitierend"),
                        ("direct_figure_speech", "autonome, direkte Figurenrede"),
                        ("direct_speech", "direkte Rede"),
                        ("indirect_speech", "indirekte Rede"),
                        ("narrated_monologue", "erlebte Rede"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Figurenrede",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="analysis_focalization",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("zero", "Nullfokalisierung"),
                        ("internal_variable", "interne Fokalisierung – variabel"),
                        ("internal_fixed", "interne Fokalisierung – fixiert"),
                        ("external", "externe Fokalisierung"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Fokalisierung",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="analysis_narrative_chronology",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("prior", "früheres Erzählen"),
                        ("simultaneous", "gleichzeitiges Erzählen"),
                        ("subsequent", "späteres Erzählen"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Zeitpunkt des Erzählens",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="analysis_narrative_level",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("extra", "extradiegetisch"),
                        ("intra", "intradiegetisch"),
                        ("meta", "metadiegetisch"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Ort des Erzählens",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="analysis_narrative_situation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("authorial", "auktorial"),
                        ("neutral", "neutral"),
                        ("figural", "personal"),
                        ("first-person", "Ich-Erzähler*in"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Erzählperspektive",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="analysis_narrative_voice",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("heterodiegetic", "heterodiegetisches Erzählen"),
                        (
                            "homodiegetic_uninvolved",
                            "homodiegetisches Erzählen – unbeteiligter Beobachter:in",
                        ),
                        (
                            "homodiegetic_participant",
                            "homodiegetisches Erzählen – beteiligter Beobachter:in",
                        ),
                        (
                            "homodiegetic_character",
                            "homodiegetisches Erzählen – Nebenfigur",
                        ),
                        (
                            "homodiegetic_protagonist",
                            "homodiegetisches Erzählen – Hauptfigur",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Stellung des:der Erzähler:in zum Geschehen",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="analysis_representation_of_thought",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("quoted_monologue", "Zitat"),
                        ("psycho_narration", "erzählter Monolog"),
                        ("autonomous_monologue", "autonomer Monolog"),
                        ("stream_of_consciousness", "Bewusstseinsstrom"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Darstellung von Gedanken",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="analysis_temporal_duration",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("scene", "Szene"),
                        ("stretch", "Dehnung"),
                        ("summary", "Raffung"),
                        ("ellipsis", "Ellipse"),
                        ("pause", "Pause"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Dauer",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="analysis_temporal_frequency",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("singulative", "singulativ"),
                        ("repetitive", "repetitiv"),
                        ("iterative", "iterativ"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Frequenz",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="analysis_temporal_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("chronological", "chronologisch"),
                        ("anachronic", "anachronisch"),
                        ("achronic", "achronisch"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Erzählordnung",
            ),
        ),
    ]
