# Generated by Django 4.2.13 on 2024-07-17 11:38

from django.db import migrations

from apis_ontology.models import LanguageMixin


def copy_language_to_new_field(apps, schema_editor):
    Expression = apps.get_model("apis_ontology", "Expression")
    VersionExpression = apps.get_model("apis_ontology", "VersionExpression")
    VersionWork = apps.get_model("apis_ontology", "VersionWork")
    Work = apps.get_model("apis_ontology", "Work")
    lang_map = {}
    for v in LanguageMixin.LanguagesIso6393:
        lang_map[v.value] = v.label
    for model in [Expression, Work, VersionExpression, VersionWork]:
        for obj in model.objects.all():
            obj.language_new = [
                lang.strip() for lang in str(obj.language).split(",") if len(lang) > 0
            ]
            if hasattr(obj, "skip_history_when_saving"):
                obj.skip_history_when_saving = True
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0065_expression_language_new_and_more"),
    ]

    operations = [
        migrations.RunPython(
            copy_language_to_new_field, reverse_code=migrations.RunPython.noop
        ),
    ]
