# Generated by Django 4.2.13 on 2024-07-18 09:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0067_alter_expression_language_new_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expression",
            name="language",
        ),
        migrations.RemoveField(
            model_name="versionexpression",
            name="language",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="language",
        ),
        migrations.RemoveField(
            model_name="work",
            name="language",
        ),
        migrations.AlterField(
            model_name="expression",
            name="language_new",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name="Sprache",
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="language_new",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name="Sprache",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="language_new",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name="Sprache",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="language_new",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name="Sprache",
            ),
        ),
    ]
