# Generated by Django 4.2.13 on 2024-07-18 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0068_remove_expression_language_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expression",
            old_name="language_new",
            new_name="language",
        ),
        migrations.RenameField(
            model_name="versionexpression",
            old_name="language_new",
            new_name="language",
        ),
        migrations.RenameField(
            model_name="versionwork",
            old_name="language_new",
            new_name="language",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="language_new",
            new_name="language",
        ),
    ]
