# Generated by Django 4.2.13 on 2024-07-22 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0070_migrate_work_data_singlechoice_to_arrayfields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionwork",
            name="figure_speech",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="focalization",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="narrative_chronology",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="narrative_level",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="narrative_situation",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="narrative_voice",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="representation_of_thought",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="temporal_duration",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="temporal_frequency",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="temporal_order",
        ),
        migrations.RemoveField(
            model_name="work",
            name="figure_speech",
        ),
        migrations.RemoveField(
            model_name="work",
            name="focalization",
        ),
        migrations.RemoveField(
            model_name="work",
            name="narrative_chronology",
        ),
        migrations.RemoveField(
            model_name="work",
            name="narrative_level",
        ),
        migrations.RemoveField(
            model_name="work",
            name="narrative_situation",
        ),
        migrations.RemoveField(
            model_name="work",
            name="narrative_voice",
        ),
        migrations.RemoveField(
            model_name="work",
            name="representation_of_thought",
        ),
        migrations.RemoveField(
            model_name="work",
            name="temporal_duration",
        ),
        migrations.RemoveField(
            model_name="work",
            name="temporal_frequency",
        ),
        migrations.RemoveField(
            model_name="work",
            name="temporal_order",
        ),
    ]
