# Generated by Django 4.2.13 on 2024-07-25 15:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0072_rename_analysis_figure_speech_versionwork_figure_speech_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionwork",
            name="narrative_voice",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("heterodiegetic", "heterodiegetisches Erzählen"),
                        (
                            "homodiegetic_uninvolved",
                            "homodiegetisches Erzählen – unbeteiligter Beobachter:in",
                        ),
                        (
                            "homodiegetic_participant",
                            "homodiegetisches Erzählen – beteiligter Beobachter:in",
                        ),
                        (
                            "homodiegetic_character",
                            "homodiegetisches Erzählen – Nebenfigur",
                        ),
                        (
                            "homodiegetic_protagonist",
                            "homodiegetisches Erzählen – Hauptfigur",
                        ),
                    ],
                    max_length=400,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Stellung des:der Erzähler:in zum Geschehen",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_voice",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("heterodiegetic", "heterodiegetisches Erzählen"),
                        (
                            "homodiegetic_uninvolved",
                            "homodiegetisches Erzählen – unbeteiligter Beobachter:in",
                        ),
                        (
                            "homodiegetic_participant",
                            "homodiegetisches Erzählen – beteiligter Beobachter:in",
                        ),
                        (
                            "homodiegetic_character",
                            "homodiegetisches Erzählen – Nebenfigur",
                        ),
                        (
                            "homodiegetic_protagonist",
                            "homodiegetisches Erzählen – Hauptfigur",
                        ),
                    ],
                    max_length=400,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Stellung des:der Erzähler:in zum Geschehen",
            ),
        ),
    ]
