# Generated by Django 4.2.13 on 2024-07-25 15:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0073_alter_versionwork_narrative_voice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="new_fictionality",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("fictional_character", "fiktive Figur"),
                        ("historical_character", "historische Figur"),
                        ("mythical_character", "mythologische Figur"),
                    ],
                    max_length=255,
                ),
                default=list,
                help_text="Faktizität vs. Fiktionalität",
                size=None,
                verbose_name="Erfindungsgrad",
            ),
        ),
        migrations.AddField(
            model_name="expression",
            name="new_edition_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("first_edition", "Erstausgabe"),
                        ("reference_edition", "Referenzausgabe"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                help_text="Zur Markierung speziell relevanter Ausgaben",
                size=None,
                verbose_name="Ausgabetyp",
            ),
        ),
        migrations.AddField(
            model_name="versioncharacter",
            name="new_fictionality",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("fictional_character", "fiktive Figur"),
                        ("historical_character", "historische Figur"),
                        ("mythical_character", "mythologische Figur"),
                    ],
                    max_length=255,
                ),
                default=list,
                help_text="Faktizität vs. Fiktionalität",
                size=None,
                verbose_name="Erfindungsgrad",
            ),
        ),
        migrations.AddField(
            model_name="versionexpression",
            name="new_edition_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("first_edition", "Erstausgabe"),
                        ("reference_edition", "Referenzausgabe"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                help_text="Zur Markierung speziell relevanter Ausgaben",
                size=None,
                verbose_name="Ausgabetyp",
            ),
        ),
    ]
