# Generated by Django 4.2.13 on 2024-07-26 12:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0074_character_new_fictionality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="fictionality",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("fictional_character", "fiktive Figur"),
                    ("historical_character", "historische Figur"),
                    ("mythical_character", "mythologische Figur"),
                ],
                default="",
                editable=False,
                help_text="Faktizität vs. Fiktionalität",
                max_length=255,
                verbose_name="Erfindungsgrad (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="edition_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("first_edition", "Erstausgabe"),
                    ("reference_edition", "Referenzausgabe"),
                ],
                default="",
                editable=False,
                help_text="Zur Markierung speziell relevanter Ausgaben",
                max_length=255,
                verbose_name="Ausgabetyp (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="versioncharacter",
            name="fictionality",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("fictional_character", "fiktive Figur"),
                    ("historical_character", "historische Figur"),
                    ("mythical_character", "mythologische Figur"),
                ],
                default="",
                editable=False,
                help_text="Faktizität vs. Fiktionalität",
                max_length=255,
                verbose_name="Erfindungsgrad (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="edition_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("first_edition", "Erstausgabe"),
                    ("reference_edition", "Referenzausgabe"),
                ],
                default="",
                editable=False,
                help_text="Zur Markierung speziell relevanter Ausgaben",
                max_length=255,
                verbose_name="Ausgabetyp (deprecated)",
            ),
        ),
    ]
