# Generated by Django 4.2.15 on 2024-09-02 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0076_migrate_multiselectfield_data_to_arrayfields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="fictionality",
        ),
        migrations.RemoveField(
            model_name="expression",
            name="edition_type",
        ),
        migrations.RemoveField(
            model_name="versioncharacter",
            name="fictionality",
        ),
        migrations.RemoveField(
            model_name="versionexpression",
            name="edition_type",
        ),
    ]
