# Generated by Django 4.2.15 on 2024-09-02 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0077_remove_character_fictionality_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="new_fictionality",
            new_name="fictionality",
        ),
        migrations.RenameField(
            model_name="expression",
            old_name="new_edition_type",
            new_name="edition_type",
        ),
        migrations.RenameField(
            model_name="versioncharacter",
            old_name="new_fictionality",
            new_name="fictionality",
        ),
        migrations.RenameField(
            model_name="versionexpression",
            old_name="new_edition_type",
            new_name="edition_type",
        ),
    ]
