# Generated by Django 4.2.15 on 2024-09-02 18:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0080_data_migration_update_textchoices_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="fictionality",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("fiktive Figur", "fiktive Figur"),
                        ("historische Figur", "historische Figur"),
                        ("mythologische Figur", "mythologische Figur"),
                    ],
                    max_length=255,
                ),
                default=list,
                help_text="Faktizität vs. Fiktionalität",
                size=None,
                verbose_name="Erfindungsgrad",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="relevancy",
            field=models.CharField(
                choices=[
                    ("Hauptfigur", "Hauptfigur"),
                    ("Nebenfigur", "Nebenfigur"),
                    ("erwähnte Figur", "erwähnte Figur"),
                ],
                default="",
                help_text="Bedeutsamkeit für den Text, Erzählfokus",
                max_length=255,
                verbose_name="Relevanz",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="edition_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Erstausgabe", "Erstausgabe"),
                        ("Referenzausgabe", "Referenzausgabe"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                help_text="Zur Markierung speziell relevanter Ausgaben",
                size=None,
                verbose_name="Ausgabetyp",
            ),
        ),
        migrations.AlterField(
            model_name="versioncharacter",
            name="fictionality",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("fiktive Figur", "fiktive Figur"),
                        ("historische Figur", "historische Figur"),
                        ("mythologische Figur", "mythologische Figur"),
                    ],
                    max_length=255,
                ),
                default=list,
                help_text="Faktizität vs. Fiktionalität",
                size=None,
                verbose_name="Erfindungsgrad",
            ),
        ),
        migrations.AlterField(
            model_name="versioncharacter",
            name="relevancy",
            field=models.CharField(
                choices=[
                    ("Hauptfigur", "Hauptfigur"),
                    ("Nebenfigur", "Nebenfigur"),
                    ("erwähnte Figur", "erwähnte Figur"),
                ],
                default="",
                help_text="Bedeutsamkeit für den Text, Erzählfokus",
                max_length=255,
                verbose_name="Relevanz",
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="edition_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Erstausgabe", "Erstausgabe"),
                        ("Referenzausgabe", "Referenzausgabe"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                help_text="Zur Markierung speziell relevanter Ausgaben",
                size=None,
                verbose_name="Ausgabetyp",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="figure_speech",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("direkt zitierend", "direkt zitierend"),
                        (
                            "autonome, direkte Figurenrede",
                            "autonome, direkte Figurenrede",
                        ),
                        ("direkte Rede", "direkte Rede"),
                        ("indirekte Rede", "indirekte Rede"),
                        ("erlebte Rede", "erlebte Rede"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Figurenrede",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="focalization",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Nullfokalisierung", "Nullfokalisierung"),
                        (
                            "interne Fokalisierung – variabel",
                            "interne Fokalisierung – variabel",
                        ),
                        (
                            "interne Fokalisierung – fixiert",
                            "interne Fokalisierung – fixiert",
                        ),
                        ("externe Fokalisierung", "externe Fokalisierung"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Fokalisierung",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="narrative_chronology",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("früheres Erzählen", "früheres Erzählen"),
                        ("gleichzeitiges Erzählen", "gleichzeitiges Erzählen"),
                        ("späteres Erzählen", "späteres Erzählen"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Zeitpunkt des Erzählens",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="narrative_level",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("extradiegetisch", "extradiegetisch"),
                        ("intradiegetisch", "intradiegetisch"),
                        ("metadiegetisch", "metadiegetisch"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Ort des Erzählens",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="narrative_situation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("auktorial", "auktorial"),
                        ("neutral", "neutral"),
                        ("personal", "personal"),
                        ("Ich-Erzähler*in", "Ich-Erzähler*in"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Erzählperspektive",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="narrative_voice",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("heterodiegetisches Erzählen", "heterodiegetisches Erzählen"),
                        (
                            "homodiegetisches Erzählen – unbeteiligter Beobachter:in",
                            "homodiegetisches Erzählen – unbeteiligter Beobachter:in",
                        ),
                        (
                            "homodiegetisches Erzählen – beteiligter Beobachter:in",
                            "homodiegetisches Erzählen – beteiligter Beobachter:in",
                        ),
                        (
                            "homodiegetisches Erzählen – Nebenfigur",
                            "homodiegetisches Erzählen – Nebenfigur",
                        ),
                        (
                            "homodiegetisches Erzählen – Hauptfigur",
                            "homodiegetisches Erzählen – Hauptfigur",
                        ),
                    ],
                    max_length=400,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Stellung des:der Erzähler:in zum Geschehen",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="representation_of_thought",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Zitat", "Zitat"),
                        ("erzählter Monolog", "erzählter Monolog"),
                        ("autonomer Monolog", "autonomer Monolog"),
                        ("Bewusstseinsstrom", "Bewusstseinsstrom"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Darstellung von Gedanken",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="temporal_duration",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Szene", "Szene"),
                        ("Dehnung", "Dehnung"),
                        ("Raffung", "Raffung"),
                        ("Ellipse", "Ellipse"),
                        ("Pause", "Pause"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Dauer",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="temporal_frequency",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("singulative", "singulativ"),
                        ("repetitiv", "repetitiv"),
                        ("iterativ", "iterativ"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Frequenz",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="temporal_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("chronologisch", "chronologisch"),
                        ("anachronisch", "anachronisch"),
                        ("achronisch", "achronisch"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Erzählordnung",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="figure_speech",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("direkt zitierend", "direkt zitierend"),
                        (
                            "autonome, direkte Figurenrede",
                            "autonome, direkte Figurenrede",
                        ),
                        ("direkte Rede", "direkte Rede"),
                        ("indirekte Rede", "indirekte Rede"),
                        ("erlebte Rede", "erlebte Rede"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Figurenrede",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="focalization",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Nullfokalisierung", "Nullfokalisierung"),
                        (
                            "interne Fokalisierung – variabel",
                            "interne Fokalisierung – variabel",
                        ),
                        (
                            "interne Fokalisierung – fixiert",
                            "interne Fokalisierung – fixiert",
                        ),
                        ("externe Fokalisierung", "externe Fokalisierung"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Fokalisierung",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_chronology",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("früheres Erzählen", "früheres Erzählen"),
                        ("gleichzeitiges Erzählen", "gleichzeitiges Erzählen"),
                        ("späteres Erzählen", "späteres Erzählen"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Zeitpunkt des Erzählens",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_level",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("extradiegetisch", "extradiegetisch"),
                        ("intradiegetisch", "intradiegetisch"),
                        ("metadiegetisch", "metadiegetisch"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Ort des Erzählens",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_situation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("auktorial", "auktorial"),
                        ("neutral", "neutral"),
                        ("personal", "personal"),
                        ("Ich-Erzähler*in", "Ich-Erzähler*in"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Erzählperspektive",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="narrative_voice",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("heterodiegetisches Erzählen", "heterodiegetisches Erzählen"),
                        (
                            "homodiegetisches Erzählen – unbeteiligter Beobachter:in",
                            "homodiegetisches Erzählen – unbeteiligter Beobachter:in",
                        ),
                        (
                            "homodiegetisches Erzählen – beteiligter Beobachter:in",
                            "homodiegetisches Erzählen – beteiligter Beobachter:in",
                        ),
                        (
                            "homodiegetisches Erzählen – Nebenfigur",
                            "homodiegetisches Erzählen – Nebenfigur",
                        ),
                        (
                            "homodiegetisches Erzählen – Hauptfigur",
                            "homodiegetisches Erzählen – Hauptfigur",
                        ),
                    ],
                    max_length=400,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Stellung des:der Erzähler:in zum Geschehen",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="representation_of_thought",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Zitat", "Zitat"),
                        ("erzählter Monolog", "erzählter Monolog"),
                        ("autonomer Monolog", "autonomer Monolog"),
                        ("Bewusstseinsstrom", "Bewusstseinsstrom"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Darstellung von Gedanken",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="temporal_duration",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Szene", "Szene"),
                        ("Dehnung", "Dehnung"),
                        ("Raffung", "Raffung"),
                        ("Ellipse", "Ellipse"),
                        ("Pause", "Pause"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Dauer",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="temporal_frequency",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("singulative", "singulativ"),
                        ("repetitiv", "repetitiv"),
                        ("iterativ", "iterativ"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Frequenz",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="temporal_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("chronologisch", "chronologisch"),
                        ("anachronisch", "anachronisch"),
                        ("achronisch", "achronisch"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Erzählordnung",
            ),
        ),
    ]
