# Generated by Django 4.2.15 on 2024-09-04 10:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0081_alter_character_fictionality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionwork",
            name="representation_of_thought",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("indirekte Rede", "indirekte Rede"),
                        ("erlebte Rede", "erlebte Rede"),
                        ("Zitat", "Zitat"),
                        ("erzählter Monolog", "erzählter Monolog"),
                        ("autonomer Monolog", "autonomer Monolog"),
                        ("Bewusstseinsstrom", "Bewusstseinsstrom"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Darstellung von Gedanken",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="representation_of_thought",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("indirekte Rede", "indirekte Rede"),
                        ("erlebte Rede", "erlebte Rede"),
                        ("Zitat", "Zitat"),
                        ("erzählter Monolog", "erzählter Monolog"),
                        ("autonomer Monolog", "autonomer Monolog"),
                        ("Bewusstseinsstrom", "Bewusstseinsstrom"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Darstellung von Gedanken",
            ),
        ),
    ]
