# Generated by Django 4.2.15 on 2024-09-04 11:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0082_alter_versionwork_representation_of_thought_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionwork",
            name="representation_of_thought",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Bewusstseinsbericht", "Bewusstseinsbericht"),
                        ("indirekte Rede", "indirekte Rede"),
                        ("erlebte Rede", "erlebte Rede"),
                        ("Gedankenzitat", "Gedankenzitat"),
                        ("innerer Monolog", "innerer Monolog"),
                        ("Bewusstseinsstrom", "Bewusstseinsstrom"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Darstellung von Gedanken",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="representation_of_thought",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Bewusstseinsbericht", "Bewusstseinsbericht"),
                        ("indirekte Rede", "indirekte Rede"),
                        ("erlebte Rede", "erlebte Rede"),
                        ("Gedankenzitat", "Gedankenzitat"),
                        ("innerer Monolog", "innerer Monolog"),
                        ("Bewusstseinsstrom", "Bewusstseinsstrom"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Darstellung von Gedanken",
            ),
        ),
    ]
