# Generated by Django 4.2.15 on 2024-09-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0084_data_migration_update_textchoices_values"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="versionarchive",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical archiv",
                "verbose_name_plural": "historical archive",
            },
        ),
        migrations.AlterModelOptions(
            name="versioncharacter",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical figur",
                "verbose_name_plural": "historical figuren",
            },
        ),
        migrations.AlterModelOptions(
            name="versiondatasource",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical datenquelle",
                "verbose_name_plural": "historical datenquellen",
            },
        ),
        migrations.AlterModelOptions(
            name="versionexpression",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical werksexpression",
                "verbose_name_plural": "historical werksexpressionen",
            },
        ),
        migrations.AlterModelOptions(
            name="versioninterpretatem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical interpretatem",
                "verbose_name_plural": "historical interpretateme",
            },
        ),
        migrations.AlterModelOptions(
            name="versionmetacharacter",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical metafigur",
                "verbose_name_plural": "historical metafiguren",
            },
        ),
        migrations.AlterModelOptions(
            name="versionorganisation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical körperschaft",
                "verbose_name_plural": "historical körperschaften",
            },
        ),
        migrations.AlterModelOptions(
            name="versionperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person",
                "verbose_name_plural": "historical personen",
            },
        ),
        migrations.AlterModelOptions(
            name="versionphysicalobject",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical vorlassobjekt",
                "verbose_name_plural": "historical vorlassobjekte",
            },
        ),
        migrations.AlterModelOptions(
            name="versionplace",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ort",
                "verbose_name_plural": "historical orte",
            },
        ),
        migrations.AlterModelOptions(
            name="versionresearchperspective",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical forschungshinsicht",
                "verbose_name_plural": "historical forschungshinsichten",
            },
        ),
        migrations.AlterModelOptions(
            name="versiontopic",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical thema",
                "verbose_name_plural": "historical themen",
            },
        ),
        migrations.AlterModelOptions(
            name="versionwork",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical werk",
                "verbose_name_plural": "historical werke",
            },
        ),
        migrations.AlterModelOptions(
            name="versionworktype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical werktyp",
                "verbose_name_plural": "historical werktypen",
            },
        ),
        migrations.AlterField(
            model_name="archive",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="fallback_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Namens-Ersatzfeld, falls weder Vor- noch Nachname eindeutig als solche festgelegt bzw. eingegeben werden können",
                max_length=255,
                verbose_name="uneindeutiger Name",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="relevancy",
            field=models.CharField(
                choices=[
                    ("Hauptfigur", "Hauptfigur"),
                    ("Nebenfigur", "Nebenfigur"),
                    ("erwähnte Figur", "erwähnte Figur"),
                ],
                default="",
                help_text="Bedeutsamkeit für den Text; Erzählfokus",
                max_length=255,
                verbose_name="Relevanz",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="edition",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Print-/Druckausgabe (Freitext)",
                max_length=255,
                verbose_name="Ausgabe",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="issue",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nummer bzw. Kennung einer Ausgabe eines periodischen Mediums",
                max_length=30,
                verbose_name="Zeitungsnummer",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="page_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Seitenanzahl"
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="publication_date_manual_input",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Akzeptierte Formate u.a.: 1.1.1920, 12/2010, 1999-12-23",
                verbose_name="Erscheinungsdatum (manuelle Eingabe)",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="relevant_pages",
            field=models.CharField(
                blank=True, default="", verbose_name="forschungsrelevante Seiten"
            ),
        ),
        migrations.AlterField(
            model_name="interpretatem",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="metacharacter",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="fallback_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Namens-Ersatzfeld, falls weder Vor- noch Nachname eindeutig als solche festgelegt bzw. eingegeben werden können",
                max_length=255,
                verbose_name="uneindeutiger Name",
            ),
        ),
        migrations.AlterField(
            model_name="physicalobject",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Breitengrad", null=True, verbose_name="Latitüde"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Längengrad", null=True, verbose_name="Longitüde"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="researchperspective",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="researchperspective",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="versionarchive",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="versioncharacter",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="versioncharacter",
            name="fallback_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Namens-Ersatzfeld, falls weder Vor- noch Nachname eindeutig als solche festgelegt bzw. eingegeben werden können",
                max_length=255,
                verbose_name="uneindeutiger Name",
            ),
        ),
        migrations.AlterField(
            model_name="versioncharacter",
            name="relevancy",
            field=models.CharField(
                choices=[
                    ("Hauptfigur", "Hauptfigur"),
                    ("Nebenfigur", "Nebenfigur"),
                    ("erwähnte Figur", "erwähnte Figur"),
                ],
                default="",
                help_text="Bedeutsamkeit für den Text; Erzählfokus",
                max_length=255,
                verbose_name="Relevanz",
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="edition",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Print-/Druckausgabe (Freitext)",
                max_length=255,
                verbose_name="Ausgabe",
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="issue",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nummer bzw. Kennung einer Ausgabe eines periodischen Mediums",
                max_length=30,
                verbose_name="Zeitungsnummer",
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="page_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Seitenanzahl"
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="publication_date_manual_input",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Akzeptierte Formate u.a.: 1.1.1920, 12/2010, 1999-12-23",
                verbose_name="Erscheinungsdatum (manuelle Eingabe)",
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="relevant_pages",
            field=models.CharField(
                blank=True, default="", verbose_name="forschungsrelevante Seiten"
            ),
        ),
        migrations.AlterField(
            model_name="versioninterpretatem",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="versionmetacharacter",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="versionorganisation",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="versionorganisation",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="fallback_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Namens-Ersatzfeld, falls weder Vor- noch Nachname eindeutig als solche festgelegt bzw. eingegeben werden können",
                max_length=255,
                verbose_name="uneindeutiger Name",
            ),
        ),
        migrations.AlterField(
            model_name="versionphysicalobject",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Breitengrad", null=True, verbose_name="Latitüde"
            ),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Längengrad", null=True, verbose_name="Longitüde"
            ),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="versionresearchperspective",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="versionresearchperspective",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="versiontopic",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="versiontopic",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="versionworktype",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="versionworktype",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pseudonym, Alias",
                max_length=255,
                verbose_name="alternativer Name",
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
    ]
