# Generated by Django 4.2.15 on 2024-09-19 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0085_alter_versionarchive_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionwork",
            name="temporal_frequency",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("singulativ", "singulativ"),
                        ("repetitiv", "repetitiv"),
                        ("iterativ", "iterativ"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Frequenz",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="temporal_frequency",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("singulativ", "singulativ"),
                        ("repetitiv", "repetitiv"),
                        ("iterativ", "iterativ"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Frequenz",
            ),
        ),
    ]
