# Generated by Django 5.1.2 on 2025-04-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0088_glossar_versionglossar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionwork",
            name="siglum",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Sigle",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="siglum",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Sigle"
            ),
        ),
    ]
