# Generated by Django 5.1.2 on 2025-06-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0089_alter_versionwork_siglum_alter_work_siglum"),
    ]

    operations = [
        migrations.AddField(
            model_name="versionwork",
            name="include_for_search",
            field=models.BooleanField(
                default=True, verbose_name="In Suche inkludieren"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="include_for_search",
            field=models.BooleanField(
                default=True, verbose_name="In Suche inkludieren"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="relevancy",
            field=models.CharField(
                choices=[
                    ("Hauptfigur", "Hauptfigur"),
                    ("Nebenfigur", "Nebenfigur"),
                    ("erwähnte Figur", "erwähnte Figur"),
                    ("k.A.", "k.A."),
                ],
                default="k.A.",
                help_text="Bedeutsamkeit für den Text; Erzählfokus",
                max_length=255,
                verbose_name="Relevanz",
            ),
        ),
        migrations.AlterField(
            model_name="versioncharacter",
            name="relevancy",
            field=models.CharField(
                choices=[
                    ("Hauptfigur", "Hauptfigur"),
                    ("Nebenfigur", "Nebenfigur"),
                    ("erwähnte Figur", "erwähnte Figur"),
                    ("k.A.", "k.A."),
                ],
                default="k.A.",
                help_text="Bedeutsamkeit für den Text; Erzählfokus",
                max_length=255,
                verbose_name="Relevanz",
            ),
        ),
    ]
