# Generated by Django 5.1.2 on 2025-06-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0090_versionwork_include_for_search_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="versionwork",
            name="primary_work",
            field=models.BooleanField(default=False, verbose_name="Primärwerk"),
        ),
        migrations.AddField(
            model_name="work",
            name="primary_work",
            field=models.BooleanField(default=False, verbose_name="Primärwerk"),
        ),
    ]
