# Generated by Django 5.1.2 on 2025-06-05 08:18

from django.db import migrations


def set_primary_work(apps, schema_editor):
    tt = apps.get_model("apis_relations", "TempTriple")
    work = apps.get_model("apis_ontology", "work")
    db_alias = schema_editor.connection.alias
    for pm in tt.objects.using(db_alias).filter(subj_id=19306, prop_id=24):
        work.objects.using(db_alias).filter(pk=pm.obj_id).update(primary_work=True)


def reverse_set_primary_work(apps, schema_editor):
    work = apps.get_model("apis_ontology", "Work")
    db_alias = schema_editor.connection.alias
    work.objects.using(db_alias).all().update(primary_work=False)


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0091_versionwork_primary_work_work_primary_work"),
    ]

    operations = [
        migrations.RunPython(set_primary_work, reverse_set_primary_work),
    ]
