# Generated by Django 5.1.2 on 2025-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0092_auto_20250605_1018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="issue",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nummer bzw. Kennung einer Ausgabe eines periodischen Mediums",
                max_length=255,
                verbose_name="Zeitungsnummer",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Untertitel"
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Titel"
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="volume",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Band"
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="issue",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nummer bzw. Kennung einer Ausgabe eines periodischen Mediums",
                max_length=255,
                verbose_name="Zeitungsnummer",
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Untertitel"
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Titel"
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="volume",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Band"
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Untertitel"
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Titel"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Untertitel"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Titel"
            ),
        ),
    ]
