# Generated by Django 5.1.2 on 2025-09-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0093_alter_expression_issue_alter_expression_subtitle_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=600, verbose_name="Untertitel"
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=600, verbose_name="Titel"
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=600, verbose_name="Untertitel"
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=600, verbose_name="Titel"
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=600, verbose_name="Untertitel"
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=600, verbose_name="Titel"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=600, verbose_name="Untertitel"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=600, verbose_name="Titel"
            ),
        ),
    ]
