name: Deploy Frischmuth app

on:
  push:
    # run deployment only on pushes to specific branches
    branches: ["deploy", "frischmuth/deploy"]
  # for triggering deployments manually via button in GitHub interface
  workflow_dispatch:

jobs:
  deploy:
    uses: acdh-oeaw/prosnet-workflows/.github/workflows/deploy-apis-instance.yml@v0.3.5
    secrets: inherit
