name: deploy
on:
  push:
    # Run deployment only on pushes to main, not other branches
    branches: []
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  deploy:
    uses: acdh-oeaw/prosnet-workflows/.github/workflows/deploy-apis-instance.yml@v0.3.1
    secrets: inherit
