# SPDX-FileCopyrightText: 2024 K Kollmann
# SPDX-License-Identifier: MIT

name: Run Ruff linter

on:
  # runs on opened, synchronised, reopened PRs
  pull_request:
  workflow_dispatch:

jobs:
  ruff-linter:
    uses: acdh-oeaw/prosnet-workflows/.github/workflows/poetry-ruff.yml@v0.4.4
    with:
      src: "."
      options: "check --output-format=github"
